# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisherFrameworkDependent < Formula
  desc "Framework-dependent desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "3.0.0-beta.2"
  license "MIT"
  depends_on "dotnet@10"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-macOS-arm64-framework-dependent-3.0.0-beta.2.tar.gz"
      sha256 "ff4267d4eb9f4470f181d5cc9b2f8cb22b8fa30e59dc9658755597a30d413cdb"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-macOS-framework-dependent-3.0.0-beta.2.tar.gz"
      sha256 "04a5c6707e3bb80b52512277f2b53481be4181a64f78ffe6364de78c10aaaa9a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-linux-framework-dependent-3.0.0-beta.2.tar.gz"
      sha256 "a3d0f60ec21cf61fe04e511a814738999073e7361a2cc1b94597162fdba646da"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"starblog-publisher-framework-dependent").write <<~EOS
      #!/bin/bash
      export DOTNET_ROOT="#{HOMEBREW_PREFIX}/opt/dotnet@10/libexec"
      exec "#{libexec}/StarBlogPublisher" "$@"
    EOS
    chmod 0755, bin/"starblog-publisher-framework-dependent"
  end

  test do
    assert_predicate bin/"starblog-publisher-framework-dependent", :executable?
  end
end
