# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisherSelfContained < Formula
  desc "Self-contained (non-AOT) desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "2.3.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-macOS-arm64-self-contained-2.3.4.tar.gz"
      sha256 "239e5ee4c6516915a07371fe8af5e4f66bcb2a7c85a9ac5f348ff7453ce7e707"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-macOS-self-contained-2.3.4.tar.gz"
      sha256 "dafab85ab8aec986859b180bf9e0927f354b917b3359f4713175c4ee5e7bfcd8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-linux-self-contained-2.3.4.tar.gz"
      sha256 "053599808be7de575b31f426e12e80057da1b5a0d9aee1c25a40319aceae4632"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"StarBlogPublisher" => "starblog-publisher-self-contained"
  end

  test do
    assert_predicate bin/"starblog-publisher-self-contained", :executable?
  end
end
