# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisher < Formula
  desc "Native AOT desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "3.0.0-beta.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-macOS-arm64-aot-3.0.0-beta.2.tar.gz"
      sha256 "a4c5b64ca652c053d0f85c6423ba600d8aa6ae762e57796d4f8985b894e14adc"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-macOS-aot-3.0.0-beta.2.tar.gz"
      sha256 "3a36c03b84c9d395ce5c659e3ec875bed00b6010ee8df26dee15089ec01fa6e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-linux-aot-3.0.0-beta.2.tar.gz"
      sha256 "e1e893ee874df8e119182347a56e0d4232b2fa13086f6f0a08f121fbee50c21f"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"StarBlogPublisher" => "starblog-publisher"
  end

  test do
    assert_predicate bin/"starblog-publisher", :executable?
  end
end
