# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisher < Formula
  desc "Native AOT desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "2.3.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-macOS-arm64-aot-2.3.4.tar.gz"
      sha256 "8373117c7b6d13cecc524919f2843db884bbe1a0370c8cfb37ec75d04c40f6f5"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-macOS-aot-2.3.4.tar.gz"
      sha256 "adca1d8ba71b93366e22d4f38da3689e489931485b670adcf7efe237c8e677aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-linux-aot-2.3.4.tar.gz"
      sha256 "115282b5f0716881185d4c7f47c5ae0fd880673e5d12248bb269da8f44110649"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"StarBlogPublisher" => "starblog-publisher"
  end

  test do
    assert_predicate bin/"starblog-publisher", :executable?
  end
end
