# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisherFrameworkDependent < Formula
  desc "Framework-dependent desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "2.3.4"
  license "MIT"
  depends_on "dotnet@10"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-macOS-arm64-framework-dependent-2.3.4.tar.gz"
      sha256 "716b1a3a875eb773c817f95955fb7f6ece87f818f2c72e34594b8d50bc244580"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-macOS-framework-dependent-2.3.4.tar.gz"
      sha256 "9bdca5772af7fe8a7ff166a0e92141c7824015e2e1b64308282e7603ff4a71f9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v2.3.4/StarBlogPublisher-linux-framework-dependent-2.3.4.tar.gz"
      sha256 "7d1a41c8e904603d8f782fe0d706da124374eff1caca446db865416e55949b63"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"starblog-publisher-framework-dependent").write <<~EOS
      #!/bin/bash
      export DOTNET_ROOT="#{HOMEBREW_PREFIX}/opt/dotnet@10/libexec"
      exec "#{libexec}/StarBlogPublisher" "$@"
    EOS
    chmod 0755, bin/"starblog-publisher-framework-dependent"
  end

  test do
    assert_predicate bin/"starblog-publisher-framework-dependent", :executable?
  end
end
