# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisherSelfContained < Formula
  desc "Self-contained (non-AOT) desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "3.0.0-beta.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-macOS-arm64-self-contained-3.0.0-beta.2.tar.gz"
      sha256 "adfa56dc0f2c1427435f7b588f0adfbe8c291c991a0dd351c0c4b28da94b953e"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-macOS-self-contained-3.0.0-beta.2.tar.gz"
      sha256 "9b0f640de87bb5b927c17d3a870bee49b01139fdb67277f3104a3da4e11b0651"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.2/StarBlogPublisher-linux-self-contained-3.0.0-beta.2.tar.gz"
      sha256 "c2e53bfd29911358037ec5837c32ff473a72d0e2e08245afa2613a3b4fd038dd"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"StarBlogPublisher" => "starblog-publisher-self-contained"
  end

  test do
    assert_predicate bin/"starblog-publisher-self-contained", :executable?
  end
end
