# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisher < Formula
  desc "Native AOT desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "3.0.0-beta.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-macOS-arm64-aot-3.0.0-beta.1.tar.gz"
      sha256 "fd1229a7a508098ac88f8daf01fa99b8f00bb7e0e5dcbd2d18c3209a33e37425"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-macOS-aot-3.0.0-beta.1.tar.gz"
      sha256 "ff5bdc25a3c039df268bd47fb42e1248df9ed89b6dfbf6f1c925ffffa35b3387"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-linux-aot-3.0.0-beta.1.tar.gz"
      sha256 "7bdd0ff88e979a9000bd6b27a9343b14e88570a9788075cef7ba09356b2bc337"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"StarBlogPublisher" => "starblog-publisher"
  end

  test do
    assert_predicate bin/"starblog-publisher", :executable?
  end
end
