# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisherFrameworkDependent < Formula
  desc "Framework-dependent desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "3.0.0-beta.1"
  license "MIT"
  depends_on "dotnet@10"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-macOS-arm64-framework-dependent-3.0.0-beta.1.tar.gz"
      sha256 "3a744aa13e79654de24319003e0d72700f4f4e72e0a266ca6bcdc7c373560a75"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-macOS-framework-dependent-3.0.0-beta.1.tar.gz"
      sha256 "6a34917dde88271835ca2686164a6e15b66b16e93aeacced2551e2a05322397a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-linux-framework-dependent-3.0.0-beta.1.tar.gz"
      sha256 "eb0658dc5d9a37c243daf1758666cc832ff8ffed55256c154745399b29ff996a"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"starblog-publisher-framework-dependent").write <<~EOS
      #!/bin/bash
      export DOTNET_ROOT="#{HOMEBREW_PREFIX}/opt/dotnet@10/libexec"
      exec "#{libexec}/StarBlogPublisher" "$@"
    EOS
    chmod 0755, bin/"starblog-publisher-framework-dependent"
  end

  test do
    assert_predicate bin/"starblog-publisher-framework-dependent", :executable?
  end
end
