# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-formulas.sh from the latest GitHub Release.
class StarblogPublisherSelfContained < Formula
  desc "Self-contained (non-AOT) desktop application"
  homepage "https://github.com/star-blog/starblog-publisher"
  version "3.0.0-beta.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-macOS-arm64-self-contained-3.0.0-beta.1.tar.gz"
      sha256 "e71d706584a701571d5bd5c905518d61caf253255f6c024149b8b458cb125f7c"
    end

    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-macOS-self-contained-3.0.0-beta.1.tar.gz"
      sha256 "649d58a6636d92d23dd54a34716a7e5b83557d5011aa087e216bf93b0baa049e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/star-blog/starblog-publisher/releases/download/v3.0.0-beta.1/StarBlogPublisher-linux-self-contained-3.0.0-beta.1.tar.gz"
      sha256 "fb1ce03e49aace15d88a970334f6e39f8c62f0dab22b2fb360093c9fdc1973f0"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"StarBlogPublisher" => "starblog-publisher-self-contained"
  end

  test do
    assert_predicate bin/"starblog-publisher-self-contained", :executable?
  end
end
