# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WechatClone < Formula
  desc "macOS 微信分身管理 CLI 工具"
  homepage "https://github.com/star-plan/wechat-clone"
  version "0.0.1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/star-plan/wechat-clone/releases/download/v0.0.1/wechat-clone-darwin-amd64.tar.gz"
    sha256 "ad4ca1e0dada9d3b0290c22349a55dcf88f8cfd211ced4af3471c553f1edce70"

    define_method(:install) do
      bin.install "wechat-clone"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/star-plan/wechat-clone/releases/download/v0.0.1/wechat-clone-darwin-arm64.tar.gz"
    sha256 "da7fca06ea646f3dc77d1dd992363131eca8a2d8833b47bdb857679c31fd6ff0"

    define_method(:install) do
      bin.install "wechat-clone"
    end
  end
end
